### ISSUE TITLE
Set up Browserify to port npm modules to the browser.

### ISSUE THREAD

**Issue by lancelafontaine** [SOEN-341/soen-341-project#18]
# Description

Browserify is a tool that allows the bundling of Node Package Manager (npm) modules as a bundle.js file that can be used in the browser. This is desirable because it enables use to use npm modules at our convenience on the front-end.
# Test Cases
- The developer is able to install an npm module on the backend and succesfully port and use it on the front-end.

**Comment by zephix109** [comment]
Browserify was not used for the end product of the Schedulator
