### ISSUE TITLE
Document database installation and architecture (see Deliverable 1)

### ISSUE THREAD

**Issue by lancelafontaine** [SOEN-341/soen-341-project#32]

**Comment by zephix109** [comment]
**Database tables**
  -login_info : {id, password}
  -student_record : {id, first_name, last_name, credits_completed, email}
  -courses : {course_name, type, section, start_time, end_time, day, room, semester}
  -courses_completed : {student_id, course_id}

**Architecture**
  -login_info -> authenticates -> student_record
  -student_record -> student has completed -> courses_completed
  -courses -> has prerequisites -> courses
