### ISSUE TITLE
Document project directory structure and architecture (MVC, etc.)

### ISSUE THREAD

**Issue by lancelafontaine** [SOEN-341/soen-341-project#38]

**Comment by zephix109** [comment]
-**app.js** start point of the program, contains all required libraries and technologies used by the application.
-**routes folder** contains all backend logic, communication with the database and redirection between pages.
-**views folder** contains all .ejs files, similar to html format with nodejs code integrated. These act as the templates for all pages.
-**public folder** contains all styling sheets and images.
-**models folder** contains all models and schemas for each object and collection.
-**data folder** contains the database
-**node_modules** contains all modules installed through npm and used in the Schedulator.
