### ISSUE TITLE
Fix the inconsistency of database description in previous deliverables

### ISSUE THREAD

**Issue by dodoels** [SOEN-341/soen-341-project#61]
Because now we are now using MongoDB instead of MySQL, since now we need to fix ALL the previous contents that include MySQL to MongoDB. These include deliverable 1 and 2 as following:
- Activity Estimation
- Gnat Chart
- Deployment Diagram
- Requirement & Specification (in deliverable 1)

For deliverable 3 and final submittion, we MUST fix the inconsistency.

**Comment by zephix109** [comment]
All discrepancies fixed by deliverable 3.
100% mark received
